# Generated by Django 5.1.7 on 2025-04-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceLog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Attendance',
        ),
    ]
